//>>built
/*
 Copyright 2015 The MathWorks, Inc.
 @exports MW/utils/deprecation
*/
require({cache:{"dojo/require":function(){define(["./_base/loader"],function(g){return{dynamic:0,normalize:function(e){return e},load:g.require}})},"dojo/selector/lite":function(){define(["../has","../_base/kernel"],function(g,e){var f=document.createElement("div"),b=f.matches||f.webkitMatchesSelector||f.mozMatchesSelector||f.msMatchesSelector||f.oMatchesSelector,a=f.querySelectorAll,d=/([^\s,](?:"(?:\\.|[^"])+"|'(?:\\.|[^'])+'|[^,])*)/g;g.add("dom-matches-selector",!!b);g.add("dom-qsa",!!a);var c=
function(b,d){if(p&&-1<b.indexOf(","))return p(b,d);var m=d?d.ownerDocument||d:e.doc||document,f=(a?/^([\w]*)#([\w\-]+$)|^(\.)([\w\-\*]+$)|^(\w+$)/:/^([\w]*)#([\w\-]+)(?:\s+(.*))?$|(?:^|(>|.+\s+))([\w\-\*]+)(\S*$)/).exec(b);d=d||m;if(f){var u=8===g("ie")&&g("quirks")?d.nodeType===m.nodeType:null!==d.parentNode&&9!==d.nodeType&&d.parentNode===m;if(f[2]&&u){var n=e.byId?e.byId(f[2],m):m.getElementById(f[2]);if(!n||f[1]&&f[1]!=n.tagName.toLowerCase())return[];if(d!=m)for(m=n;m!=d;)if(m=m.parentNode,
!m)return[];return f[3]?c(f[3],n):[n]}if(f[3]&&d.getElementsByClassName)return d.getElementsByClassName(f[4]);if(f[5])if(n=d.getElementsByTagName(f[5]),f[4]||f[6])b=(f[4]||"")+f[6];else return n}if(a)return 1===d.nodeType&&"object"!==d.nodeName.toLowerCase()?h(d,b,d.querySelectorAll):d.querySelectorAll(b);n||(n=d.getElementsByTagName("*"));f=[];m=0;for(u=n.length;m<u;m++){var s=n[m];1==s.nodeType&&l(s,b,d)&&f.push(s)}return f},h=function(a,b,c){var l=a,f=a.getAttribute("id"),n=f||"__dojo__",s=a.parentNode,
e=/^\s*[+~]/.test(b);if(e&&!s)return[];f?n=n.replace(/'/g,"\\$\x26"):a.setAttribute("id",n);e&&s&&(a=a.parentNode);b=b.match(d);for(s=0;s<b.length;s++)b[s]="[id\x3d'"+n+"'] "+b[s];b=b.join(",");try{return c.call(a,b)}finally{f||l.removeAttribute("id")}};if(!g("dom-matches-selector"))var l=function(){function a(b,d,c){var n=d.charAt(0);if('"'==n||"'"==n)d=d.slice(1,-1);d=d.replace(/\\/g,"");var l=s[c||""];return function(a){return(a=a.getAttribute(b))&&l(a,d)}}function b(a){return function(b,d){for(;(b=
b.parentNode)!=d;)if(a(b,d))return!0}}function d(a){return function(b,d){b=b.parentNode;return a?b!=d&&a(b,d):b==d}}function c(a,b){return a?function(d,c){return b(d)&&a(d,c)}:b}var l="div"==f.tagName?"toLowerCase":"toUpperCase",n={"":function(a){a=a[l]();return function(b){return b.tagName==a}},".":function(a){var b=" "+a+" ";return function(d){return-1<d.className.indexOf(a)&&-1<(" "+d.className+" ").indexOf(b)}},"#":function(a){return function(b){return b.id==a}}},s={"^\x3d":function(a,b){return 0==
a.indexOf(b)},"*\x3d":function(a,b){return-1<a.indexOf(b)},"$\x3d":function(a,b){return a.substring(a.length-b.length,a.length)==b},"~\x3d":function(a,b){return-1<(" "+a+" ").indexOf(" "+b+" ")},"|\x3d":function(a,b){return 0==(a+"-").indexOf(b+"-")},"\x3d":function(a,b){return a==b},"":function(a,b){return!0}},e={};return function(l,f,s){var h=e[f];if(!h){if(f.replace(/(?:\s*([> ])\s*)|(#|\.)?((?:\\.|[\w-])+)|\[\s*([\w-]+)\s*(.?=)?\s*("(?:\\.|[^"])+"|'(?:\\.|[^'])+'|(?:\\.|[^\]])*)\s*\]/g,function(l,
f,s,e,z,p,y){e?h=c(h,n[s||""](e.replace(/\\/g,""))):f?h=(" "==f?b:d)(h):z&&(h=c(h,a(z,y,p)));return""}))throw Error("Syntax error in query");if(!h)return!0;e[f]=h}return h(l,s)}}();if(!g("dom-qsa"))var p=function(a,b){for(var l=a.match(d),f=[],e=0;e<l.length;e++){a=new String(l[e].replace(/\s*$/,""));a.indexOf=escape;for(var n=c(a,b),s=0,h=n.length;s<h;s++){var p=n[s];f[p.sourceIndex]=p}}l=[];for(e in f)l.push(f[e]);return l};c.match=b?function(a,d,c){return c&&9!=c.nodeType?h(c,d,function(d){return b.call(a,
d)}):b.call(a,d)}:l;return c})},"xstyle/core/load-css":function(){define([],function(){function g(d){if(b.createStyleSheet){var c=b.createStyleSheet();c.cssText=d;return c.owningElement}c=b.createElement("style");c.setAttribute("type","text/css");c.appendChild(b.createTextNode(d));a.insertBefore(c,a.firstChild);return c}function e(d,c,e){var l=f[d];if(l)return p=g(l),c(p);var p=b.createElement("link");p.type="text/css";p.rel="stylesheet";p.href=d;var q=!e||!1!==e.wait;e=(e=navigator.userAgent.match(/AppleWebKit\/(\d+\.?\d*)/))&&
+e[1];if(null===p.onload&&!(536>e))p.onload=function(){p.onload=null;p.onerror=null;q&&c(p)},p.onerror=function(){console.error("Error loading stylesheet "+d);q&&c(p)};else if(q)var r=setInterval(function(){p.style&&(clearInterval(r),c(p))},15);(a||b.getElementsByTagName("head")[0]).appendChild(p);q||c(p)}var f="undefined"==typeof _css_cache?{}:_css_cache,b=document,a=b.head;e.insertCss=g;return e})},"dijit/main":function(){define(["dojo/_base/kernel"],function(g){return g.dijit})},"dojox/main":function(){define(["dojo/_base/kernel"],
function(g){return g.dojox})},"mw-browser-utils/BrowserCheck":function(){define("dojo/_base/window dojo/window dojo/dom-construct dojo/has dojo/i18n!./l10n/nls/unsupportedErrorPage ./detect/css ./detect/object".split(" "),function(g,e,f,b,a){var d={isBrowserValid:function(){var a=!0;b("quirks")?a=!1:b("css-enabled")?b("css-border-radius")?b("css-text-overflow")?b("object-create")||(a=!1):a=!1:a=!1:a=!1;return a},displayErrorAsOverlay:function(){f.create("div",{style:{position:"absolute",left:"0%",
top:"0%","background-color":"grey","-moz-opacity":"0.7",opacity:".70",filter:"alpha(opacity\x3d70)",width:"100%",height:"100%",zIndex:"90"},id:"fadeDiv"},g.body());f.create("div",{style:{position:"relative",margin:"auto","margin-top":"12.35%",width:"400px",height:"300px",padding:"10px",border:"2px solid black","background-color":"#ffffff","z-index":"100","font-family":"Sans-serif"},id:"unsupportedBrowser","class":"content_module"},g.body()).innerHTML=a.unsupportedError}};return{load:function(a,b,
l){d.isBrowserValid()?l():a?g.global.location=a:d.displayErrorAsOverlay()}}})},"dojo/window":function(){define("./_base/lang ./sniff ./_base/window ./dom ./dom-geometry ./dom-style ./dom-construct".split(" "),function(g,e,f,b,a,d,c){e.add("rtl-adjust-position-for-verticalScrollBar",function(b,d){var e=f.body(d),h=c.create("div",{style:{overflow:"scroll",overflowX:"visible",direction:"rtl",visibility:"hidden",position:"absolute",left:"0",top:"0",width:"64px",height:"64px"}},e,"last"),m=c.create("div",
{style:{overflow:"hidden",direction:"ltr"}},h,"last"),g=0!=a.position(m).x;h.removeChild(m);e.removeChild(h);return g});e.add("position-fixed-support",function(b,d){var e=f.body(d),h=c.create("span",{style:{visibility:"hidden",position:"fixed",left:"1px",top:"1px"}},e,"last"),m=c.create("span",{style:{position:"fixed",left:"0",top:"0"}},h,"last"),g=a.position(m).x!=a.position(h).x;h.removeChild(m);e.removeChild(h);return g});var h={getBox:function(b){b=b||f.doc;var d="BackCompat"==b.compatMode?f.body(b):
b.documentElement,c=a.docScroll(b);if(e("touch")){var g=h.get(b);b=g.innerWidth||d.clientWidth;d=g.innerHeight||d.clientHeight}else b=d.clientWidth,d=d.clientHeight;return{l:c.x,t:c.y,w:b,h:d}},get:function(a){if(e("ie")&&h!==document.parentWindow){a.parentWindow.execScript("document._parentWindow \x3d window;","Javascript");var b=a._parentWindow;a._parentWindow=null;return b}return a.parentWindow||a.defaultView},scrollIntoView:function(c,h){try{c=b.byId(c);var g=c.ownerDocument||f.doc,r=f.body(g),
m=g.documentElement||r.parentNode,v=e("ie")||e("trident"),u=e("webkit");if(!(c==r||c==m))if(!e("mozilla")&&(!v&&!u&&!e("opera")&&!e("trident")&&!e("edge"))&&"scrollIntoView"in c)c.scrollIntoView(!1);else{var n="BackCompat"==g.compatMode,s=Math.min(r.clientWidth||m.clientWidth,m.clientWidth||r.clientWidth),w=Math.min(r.clientHeight||m.clientHeight,m.clientHeight||r.clientHeight),g=u||n?r:m,x=h||a.position(c),t=c.parentNode,u=function(a){return 6>=v||7==v&&n?!1:e("position-fixed-support")&&"fixed"==
d.get(a,"position").toLowerCase()},y=this,E=function(a,b,d){"BODY"==a.tagName||"HTML"==a.tagName?y.get(a.ownerDocument).scrollBy(b,d):(b&&(a.scrollLeft+=b),d&&(a.scrollTop+=d))};if(!u(c))for(;t;){t==r&&(t=g);var k=a.position(t),B=u(t),D="rtl"==d.getComputedStyle(t).direction.toLowerCase();if(t==g){k.w=s;k.h=w;if(g==m&&(v||e("trident"))&&D)k.x+=g.offsetWidth-k.w;k.x=0;k.y=0}else{var C=a.getPadBorderExtents(t);k.w-=C.w;k.h-=C.h;k.x+=C.l;k.y+=C.t;var z=t.clientWidth,F=k.w-z;0<z&&0<F&&(D&&e("rtl-adjust-position-for-verticalScrollBar")&&
(k.x+=F),k.w=z);z=t.clientHeight;F=k.h-z;0<z&&0<F&&(k.h=z)}B&&(0>k.y&&(k.h+=k.y,k.y=0),0>k.x&&(k.w+=k.x,k.x=0),k.y+k.h>w&&(k.h=w-k.y),k.x+k.w>s&&(k.w=s-k.x));var G=x.x-k.x,H=x.y-k.y,J=G+x.w-k.w,K=H+x.h-k.h,A,I;if(0<J*G&&(t.scrollLeft||t==g||t.scrollWidth>t.offsetHeight)){A=Math[0>G?"max":"min"](G,J);if(D&&(8==v&&!n||5<=e("trident")))A=-A;I=t.scrollLeft;E(t,A,0);A=t.scrollLeft-I;x.x-=A}if(0<K*H&&(t.scrollTop||t==g||t.scrollHeight>t.offsetHeight))A=Math.ceil(Math[0>H?"max":"min"](H,K)),I=t.scrollTop,
E(t,0,A),A=t.scrollTop-I,x.y-=A;t=t!=g&&!B&&t.parentNode}}}catch(L){console.error("scrollIntoView: "+L),c.scrollIntoView(!1)}}};g.setObject("dojo.window",h);return h})},"dojo/i18n":function(){define("./_base/kernel require ./has ./_base/array ./_base/config ./_base/lang ./_base/xhr ./json module".split(" "),function(g,e,f,b,a,d,c,h,l){f.add("dojo-preload-i18n-Api",1);var p=g.i18n={},q=/(^.*(^|\/)nls)(\/|$)([^\/]*)\/?([^\/]*)/,r=function(a,b,d,c){var n=[d+c];b=b.split("-");for(var e="",f=0;f<b.length;f++)if(e+=
(e?"-":"")+b[f],!a||a[e])n.push(d+e+"/"+c),n.specificity=e;return n},m={},v=function(a,b,d){d=d?d.toLowerCase():g.locale;a=a.replace(/\./g,"/");b=b.replace(/\./g,"/");return/root/i.test(d)?a+"/nls/"+b:a+"/nls/"+d+"/"+b},u=g.getL10nName=function(a,b,d){return l.id+"!"+v(a,b,d)},n=function(a,b,c,n,e,f){a([b],function(k){var s=d.clone(k.root||k.ROOT),h=r(!k._v1x&&k,e,c,n);a(h,function(){for(var a=1;a<h.length;a++)s=d.mixin(d.clone(s),arguments[a]);m[b+"/"+e]=s;s.$locale=h.specificity;f()})})},s=function(b){var c=
a.extraLocale||[],c=d.isArray(c)?c:[c];c.push(b);return c},w=function(a,c,e){if(f("dojo-preload-i18n-Api")){var l=a.split("*"),w="preload"==l[1];w&&(m[a]||(m[a]=1,E(l[2],h.parse(l[3]),1,c)),e(1));if(!(l=w))t&&y.push([a,c,e]),l=t;if(l)return}a=q.exec(a);var p=a[1]+"/",x=a[5]||a[4],r=p+x,l=(a=a[5]&&a[4])||g.locale||"",u=r+"/"+l;a=a?[l]:s(l);var v=a.length,B=function(){--v||e(d.delegate(m[u]))};b.forEach(a,function(a){var b=r+"/"+a;f("dojo-preload-i18n-Api")&&k(b);m[b]?B():n(c,r,p,x,a,B)})};f("dojo-preload-i18n-Api");
var x=p.normalizeLocale=function(a){a=a?a.toLowerCase():g.locale;return"root"==a?"ROOT":a},t=0,y=[],E=p._preloadLocalizations=function(a,c,n,f){function k(a,b){f.isXdUrl(e.toUrl(a+".js"))||n?f([a],b):C([a],b,f)}function s(a,b){for(var d=a.split("-");d.length;){if(b(d.join("-")))return;d.pop()}b("ROOT")}function l(){for(--t;!t&&y.length;)w.apply(null,y.shift())}function h(n){n=x(n);s(n,function(h){if(0<=b.indexOf(c,h)){var g=a.replace(/\./g,"/")+"_"+h;t++;k(g,function(a){for(var b in a){var c=a[b],
k=b.match(/(.+)\/([^\/]+)$/),g;if(k&&(g=k[2],k=k[1]+"/",c._localized)){var y;if("ROOT"===h){var w=y=c._localized;delete c._localized;w.root=c;m[e.toAbsMid(b)]=w}else y=c._localized,m[e.toAbsMid(k+g+"/"+h)]=c;h!==n&&function(a,b,c,k){var h=[],g=[];s(n,function(d){k[d]&&(h.push(e.toAbsMid(a+d+"/"+b)),g.push(e.toAbsMid(a+b+"/"+d)))});h.length?(t++,f(h,function(){for(var f=h.length-1;0<=f;f--)c=d.mixin(d.clone(c),arguments[f]),m[g[f]]=c;m[e.toAbsMid(a+b+"/"+n)]=d.clone(c);l()})):m[e.toAbsMid(a+b+"/"+
n)]=c}(k,g,c,y)}}l()});return!0}return!1})}f=f||e;h();b.forEach(g.config.extraLocale,h)},k=function(){},B={},D=new Function("__bundle","__checkForLegacyModules","__mid","__amdValue","var define \x3d function(mid, factory){define.called \x3d 1; __amdValue.result \x3d factory || mid;},\t   require \x3d function(){define.called \x3d 1;};try{define.called \x3d 0;eval(__bundle);if(define.called\x3d\x3d1)return __amdValue;if((__checkForLegacyModules \x3d __checkForLegacyModules(__mid)))return __checkForLegacyModules;}catch(e){}try{return eval('('+__bundle+')');}catch(e){return e;}"),
C=function(a,d,n){var f=[];b.forEach(a,function(a){function b(c){c=D(c,k,a,B);c===B?f.push(m[d]=B.result):(c instanceof Error&&(console.error("failed to evaluate i18n bundle; url\x3d"+d,c),c={}),f.push(m[d]=/nls\/[^\/]+\/[^\/]+$/.test(d)?c:{root:c,_v1x:1}))}var d=n.toUrl(a+".js");if(m[d])f.push(m[d]);else{var e=n.syncLoadNls(a);e||(e=k(a.replace(/nls\/([^\/]*)\/([^\/]*)$/,"nls/$2/$1")));if(e)f.push(e);else if(c)c.get({url:d,sync:!0,load:b,error:function(){f.push(m[d]={})}});else try{n.getText(d,!0,
b)}catch(h){f.push(m[d]={})}}});d&&d.apply(null,f)},k=function(a){for(var b,d=a.split("/"),c=g.global[d[0]],n=1;c&&n<d.length-1;c=c[d[n++]]);c&&((b=c[d[n]])||(b=c[d[n].replace(/-/g,"_")]),b&&(m[a]=b));return b};p.getLocalization=function(a,b,d){var c;a=v(a,b,d);w(a,!e.isXdUrl(e.toUrl(a+".js"))?function(a,b){C(a,b,e)}:e,function(a){c=a});return c};return d.mixin(p,{dynamic:!0,normalize:function(a,b){return/^\./.test(a)?b(a):a},load:w,cache:m,getL10nName:u})})},"mw-browser-utils/detect/css":function(){define(["dojo/has"],
function(g){function e(a,b){var c=!1,e=a.charAt(0).toUpperCase()+a.slice(1),l=f.length,g=b.style;if("string"===typeof g[a])c=!0;else for(;l;)if(l-=1,"string"===typeof g[f[l]+e]){c=!0;break}return c}var f=["Webkit","Moz","O","ms","Khtml"],b=g.add;b("css-enabled",function(a,b,c){var f;a=b.documentElement;var e;if(!(e=b.body))f=!0,e=a.insertBefore(b.createElement("body"),a.firstChild);a=e;e=c.style.display;c.style.display="none";a.insertBefore(c,a.firstChild);b=0===c.offsetWidth;a.removeChild(c);c.style.display=
e;f&&a.parentNode.removeChild(a);return b});b("css-content-box",function(a,b,c){var e,f;a=b.documentElement;var p=null;if(g("css-enabled")){if(!(f=b.body))e=!0,f=a.insertBefore(b.createElement("body"),a.firstChild);c.style.cssText="position: absolute; top: -4000px; width: 40px; height: 40px; border: 1px solid black;";f.insertBefore(c,f.firstChild);p=40===c.clientWidth;f.removeChild(c);c.style.cssText=""}e&&f.parentNode.removeChild(f);return p});b("css-position-fixed",function(a,b,c){var f,e,p=b.documentElement,
q=null;if(g("css-enabled")){a=c.cloneNode(!1);if(!(e=b.body))f=!0,e=p.insertBefore(b.createElement("body"),p.firstChild);b=e.style.cssText;e.style.cssText="padding:0;margin:0";c.style.cssText="position:fixed;top:42px";e.insertBefore(a,e.firstChild);e.insertBefore(c,a);q=c.offsetTop!==a.offsetTop;e.removeChild(c);e.removeChild(a);e.style.cssText=b;c.style.cssText=""}f&&e.parentNode.removeChild(e);return q});b("css-rgba",function(a,b,c){a=/^rgba/;b=null;if(g("css-enabled"))try{c.style.color="rgba(1,1,1,0.5)",
b=a.test(c.style.color),c.style.color=""}catch(e){}return b});b("css-border-radius",function(a,b,c){return e("borderRadius",c)});b("css-box-shadow",function(a,b,c){return e("boxShadow",c)});b("css-box-sizing",function(a,b,c){return e("boxSizing",c)});b("css-opacity",function(a,b,c){return e("opacity",c)});b("css-opacity-filter",function(a,b){return!g("css-opacity")&&"undefined"!==typeof b.documentElement.filters});b("css-resize",function(a,b,c){return e("resize",c)});b("css-selectable",function(a,
b,c){return e("userSelect",c)});b("css-style-float",function(a,b,c){return e("styleFloat",c)});b("css-pointerevents",function(a,b,c){return e("pointerEvents",c)});b("css-text-overflow",function(a,b,c){return e("textOverflow",c)});b("css-text-shadow",function(a,b,c){return e("textShadow",c)});b("css-transform",function(a,b,c){return e("transform",c)});return g})},"mw-browser-utils/detect/object":function(){define(["dojo/has"],function(g){var e=g.add,f={}.toString,b=Object;e("object-create",function(){return"[object Function]"===
f.call(b.create)});e("object-getprototypeof",function(){return"[object Function]"===f.call(b.getPrototypeOf)});e("object-seal",function(){return"[object Function]"===f.call(b.seal)});e("object-freeze",function(){return"[object Function]"===f.call(b.freeze)});e("object-issealed",function(){return"[object Function]"===f.call(b.isSealed)});e("object-isfrozen",function(){return"[object Function]"===f.call(b.isFrozen)});e("object-keys",function(){return"[object Function]"===f.call(b.keys)});e("object-preventextensions",
function(){return"[object Function]"===f.call(b.preventExtensions)});e("object-isextensible",function(){return"[object Function]"===f.call(b.isExtensible)});e("object-defineproperty",function(){return"[object Function]"===f.call(b.defineProperty)});e("object-defineproperties",function(){return"[object Function]"===f.call(b.defineProperties)});e("object-getownpropertydescriptor",function(){return"[object Function]"===f.call(b.getOwnPropertyDescriptor)});e("object-getownpropertynames",function(){return"[object Function]"===
f.call(b.getOwnPropertyNames)});e("object-es5",function(){return g("object-create")&&g("object-defineproperties")&&g("object-defineproperty")&&g("object-freeze")&&g("object-getownpropertydescriptor")&&g("object-getownpropertynames")&&g("object-getprototypeof")&&g("object-isextensible")&&g("object-isfrozen")&&g("object-issealed")&&g("object-keys")&&g("object-preventextensions")&&g("object-seal")});return g})},"mw-browser-utils/MobileBrowserCheck":function(){define(["dojo/_base/window","mw-html-utils/HtmlUtils",
"dojo/has"],function(g,e,f){var b={isBrowserValid:function(){var a=!0;if(null==e.parseQueryString().touch&&(f("ios")||f("android")))a=!1;return a}};return{load:function(a,d,c){b.isBrowserValid()?c():g.global.location=a}}})},"mw-html-utils/HtmlUtils":function(){define(["dojo/io-query","mw-html-utils/_parseHtml/sanitize","mw-deprecation-utils/deprecation"],function(g,e,f){return{HYPERLINK_ESCAPE_REGEXP:/<a\s+href\s*=\s*"[^"]*"[^>]*>[\s\S]*?<\/a>/g,HYPERLINK_WITH_PARENTHESIS_ESCAPE_REGEXP:/<a\s+href\s*=\s*"([^"]*)"([^>]*)>([\s\S]*?)<\/a>/g,
STRONG_ESCAPE_REGEXP:/<strong>|<\/strong>/g,BOLD_LINK_ATTRIBUTE_REGEX:/\bstyle\s*=\s*"[^"]*\bfont-weight\s*:\s*bold\b[^"]*"/,parseQueryString:function(){var b=window.location.search.substr(1,window.location.search.length);return this._parseQueryString(b)},_parseQueryString:function(b){return g.queryToObject(b)},parseUrl:function(b){var a=document.createElement("a");a.display="none";a.href=b||window.location.href;a.href=a.href;a={protocol:a.protocol,hostname:a.hostname,port:a.port,pathname:a.pathname,
search:a.search,hash:a.hash};if(("https:"===a.protocol||"http:"===a.protocol)&&0!==a.pathname.indexOf("/"))a.pathname="/"+a.pathname;"https:"===a.protocol&&("443"===a.port&&0!==b.indexOf("https://"+a.hostname+":443"))&&(a.port="");return a},escapeHtml:function(b){var a=document.createElement("div");a.textContent=b;return a.innerHTML},escapeLinksAndHtml:function(b,a){f.deprecated({deprecated:{module:"mw-html-utils/HtmlUtils",method:"escapeLinksAndHtml"},replacement:{module:"mw-html-utils/HtmlUtils",
method:"treatHtmlLikeCommandWindow"}});var d="",c=b.split(this.HYPERLINK_ESCAPE_REGEXP),e=b.match(this.HYPERLINK_ESCAPE_REGEXP),g="",p=this,q=0,r=function(a,b,d,c){a=p.parseUrl(b).protocol;"http:"!==a&&("https:"!==a&&"matlab:"!==a)&&(b="#");b=p.escapeHtml(b);c=p._strongNotEscaped(c,!0);g='\x3ca href\x3d"'+b+'"\x3e'+c+"\x3c/a\x3e"};if(a)d=this.escapeHtml(b),d=this.escapeWhitespace(d);else if(""!==c[0]&&(d=this._strongNotEscaped(c[0],!0)),null!==e&&0!==e.length)for(q=0;q<e.length;q+=1)e[q].replace(this.HYPERLINK_WITH_PARENTHESIS_ESCAPE_REGEXP,
r),""!==c[q+1]&&(c[q+1]=this._strongNotEscaped(c[q+1],!0)),d+=g+c[q+1];return d},treatHtmlLikeCommandWindow:function(b,a,d){if("string"!==typeof b)return"";var c="",e=b.split(this.HYPERLINK_ESCAPE_REGEXP),f=b.match(this.HYPERLINK_ESCAPE_REGEXP),g="",q=this,r=0;d=d||{};var m=function(a,b,d,c){a=q.parseUrl(b).protocol;var e="";"http:"!==a&&("https:"!==a&&"matlab:"!==a)&&(b="#");b=q.escapeHtml(b);c=q._strongNotEscaped(c,!1);q.BOLD_LINK_ATTRIBUTE_REGEX.test(d)&&(e=' style\x3d"font-weight:bold"');g='\x3ca href\x3d"'+
b+'"'+e+"\x3e"+c+"\x3c/a\x3e"};if(a)c=this.escapeHtml(b);else if(""!==e[0]&&(c=this._strongNotEscaped(e[0],!1)),null!==f&&0!==f.length)for(r=0;r<f.length;r+=1)f[r].replace(this.HYPERLINK_WITH_PARENTHESIS_ESCAPE_REGEXP,m),""!==e[r+1]&&(e[r+1]=this._strongNotEscaped(e[r+1],!1)),c+=g+e[r+1];d.addPreTagToPreserveWhiteSpace&&(c='\x3cspan style\x3d"white-space: pre"\x3e'+c+"\x3c/span\x3e");return c},_strongNotEscaped:function(b,a){var d="",c=b.match(this.STRONG_ESCAPE_REGEXP),e=b.split(this.STRONG_ESCAPE_REGEXP),
f=function(a){return a};a&&(f=this.escapeWhitespace);var g=0;if(null!==c&&0!==c.length){d=f(this.escapeHtml(e[0]));for(g=0;g<c.length;g+=1)d+=c[g]+f(this.escapeHtml(e[g+1]))}else d=f(this.escapeHtml(b));return d},escapeWhitespace:function(b){f.deprecated({deprecated:{module:"mw-html-utils/HtmlUtils",method:"escapeWhitespace"},replacement:{module:"Plain HTML",method:'Set class as white-space: pre or use \x3cspan style\x3d"white-space: pre"\x3e...\x3c/span\x3e'}});return(b||"").replace(/\n/g,"\x3cbr\x3e").replace(/ {2}/g,
"\x26nbsp;\x26nbsp;")},handleAnchors:function(b,a){if(a.target.href){a.preventDefault();a.stopPropagation();var d=a.target.href;-1!==d.indexOf("matlab:")?"matlab:"===d.substring(0,7)&&(d=a.target.href.substring(7),b(window.unescape(d))):window.open(a.target.href)}},isElementOverflown:function(b){return b.scrollHeight>b.clientHeight||b.scrollWidth>b.clientWidth},sanitizeHtmlFromJava:e.sanitizeHtmlFromJava}})},"mw-html-utils/_parseHtml/sanitize":function(){define([],function(){var g="backgroundColor borderBottom borderBottomColor borderBottomLeftRadius borderBottomRightRadius borderBottomStyle borderBottomWidth borderLeft borderLeftColor borderLeftStyle borderLeftWidth borderRadius borderRight borderRightColor borderRightStyle borderRightWidth borderSpacing borderStyle borderTop borderTopColor borderTopLeftRadius borderTopRightRadius borderTopStyle borderTopWidth borderWidth color fontFamily fontSize fontStyle fontWeight height lineHeight margin marginBottom marginLeft marginRight marginTop maxHeight maxWidth minHeight minWidth overflow overflowWrap overflowX overflowY padding paddingBottom paddingLeft paddingRight paddingTop textAlign textAnchor textDecoration textIndent textOverflow textShadow textTransform width".split(" "),
e=function(e,b){var a=b.getAttribute("style");if(e.style&&null!==a&&""!==a)for(a=0;a<g.length;a+=1){var d=g[a],c=b.style[d];void 0!==e.style[d]&&(e.style[d]=c)}};return{sanitizeHtmlFromJava:function(f,b,a){return function(d){var c=function(a,d){for(var c=[],e=0;e<a.length;e+=1){var f=a[e];if(d.hasAttribute(f)){var n=d.getAttribute(f),g="";if(b[f]){var g=b[f],n=String.prototype.trim.call(n),h=n.indexOf(":");0>h&&g.relative[n.charAt(0)]?g=n:(h=n.substring(0,h),g=g[h+":"]?n:"#")}else g=n;c.push({key:f,
value:g})}}return c},g=function(b){var d=void 0;b.nodeType===window.Node.ELEMENT_NODE?f[b.tagName]?(d=document.createElement(b.tagName),c(f[b.tagName],b).forEach(function(a){d.setAttribute(a.key,a.value)}),a&&e(d,b)):d=document.createDocumentFragment():d=b.nodeType===window.Node.TEXT_NODE?document.createTextNode(b.textContent):document.createDocumentFragment();return d},l=function r(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:0,d=document.createDocumentFragment();if(150<b||!a)return d;
for(var c=a.firstChild;c;c=c.nextSibling){var e=g(c);c.nodeType===window.Node.ELEMENT_NODE&&e.appendChild(r(c,b+1));d.appendChild(e)}return d};d=(new DOMParser).parseFromString(d,"text/html");var p=void 0;return p=d.body?l(d.body):document.createDocumentFragment()}}({A:["target","href","title"],ABBR:["title"],ADDRESS:[],AREA:["shape","coords","href","alt"],ARTICLE:[],ASIDE:[],AUDIO:["autoplay","controls","loop","preload","src"],B:[],BDI:["dir"],BDO:["dir"],BIG:[],BLOCKQUOTE:["cite"],BR:[],CAPTION:[],
CENTER:[],CITE:[],CODE:[],COL:["align","valign","span","width"],COLGROUP:["align","valign","span","width"],DD:[],DEL:["datetime"],DETAILS:["open"],DIV:[],DL:[],DT:[],EM:[],FONT:["color","size","face"],FOOTER:[],H1:[],H2:[],H3:[],H4:[],H5:[],H6:[],HEADER:[],HR:[],I:[],IMG:["src","alt","title","width","height"],INS:["datetime"],LI:[],MARK:[],NAV:[],OL:[],P:[],PRE:[],S:[],SECTION:[],SMALL:[],SPAN:[],SUB:[],SUP:[],STRONG:[],TABLE:["width","border","align","valign"],TBODY:["align","valign"],TD:["width",
"rowspan","colspan","align","valign"],TFOOT:["align","valign"],TH:["width","rowspan","colspan","align","valign"],THEAD:["align","valign"],TR:["rowspan","align","valign"],TT:[],U:[],UL:[],VIDEO:"autoplay controls loop preload src height width".split(" ")},{href:{"http:":!0,"https:":!0,"mailto:":!0,"matlab:":!0,relative:{"#":!0,"/":!0}},src:{"http:":!0,"https:":!0,"mailto:":!0,relative:{"#":!0,"/":!0}}},!0)}})},"mw-deprecation-utils/deprecation":function(){define(["dojo/_base/config","mw-log/Log"],
function(g,e){var f={deprecated:function(b){var a,d;if((g.isDebug||window.showDeprecationsAsErrors)&&this._isConfigValid(b))d=window.showDeprecationsAsErrors||b.deprecationLevel===this.ERROR?this.ERROR:this.WARN,a="DEPRECATED: ",b.deprecated&&(a+=b.deprecated.module,b.deprecated.method&&(a+="."+b.deprecated.method+"()"),a+="."),b.replacement&&(a+=" Use "+b.replacement.module,b.replacement.method&&(a+="."+b.replacement.method+"()"),a+=" instead."),b.removalVersion&&(a+=" Will be removed in version: "+
b.removalVersion+"."),b.geckNumber&&(a+=" Please use g"+b.geckNumber+" to track latest information regarding this deprecation"),b.additionalInformation&&(a+=" "+b.additionalInformation),e[d](a)},_isConfigValid:function(b){var a=!!b.deprecated&&"object"===typeof b.deprecated&&b.deprecated.hasOwnProperty("module");b.replacement&&(a=a&&"object"===typeof b.replacement&&b.replacement.hasOwnProperty("module"));b.geckNumber&&(a=a&&"number"===typeof b.geckNumber);a||e.error("Supplied deprecationConfig properties are not valid. Please refer to http://inside.mathworks.com/wiki/Web_Widgets_Deprecation_API for right API");
return a}};Object.defineProperties(f,{WARN:{value:"warn",enumerable:!0},ERROR:{value:"error",enumerable:!0}});return f})},"mw-log/Log":function(){define(["dojo/date/locale"],function(g){return function(){function e(b){h&&(l||!d||!d.log)&&h.apply(a,b)}function f(b){c[b]=function(){if(0!==p&&d&&d[b])if("assert"===b){if(!arguments[0])if(a.ScriptEngine){var c=Array.prototype.slice.call(arguments);c.shift();d[b](!1,c)}else d[b].apply(d,arguments)}else if(a.ScriptEngine)if(-1!==b.indexOf("profile"))d[b]();
else d[b](arguments[0]);else d[b].apply(d,arguments)}}function b(b,f){c[f]=function(){var c=Array.prototype.slice.call(arguments),h=g.format(new Date,{selector:"date",datePattern:"h:m:s.SSS"}),l=[f].concat(c),c=[h].concat(c);q.push(l);q.length>r&&q.shift();e(l);if(d&&(0<p?p>b:m.length+p<=b))if(d.firebug&&"error"!==f)d[f].apply(a,c);else if(d[f])d[f](c);else d.log(c)}}var a=this,d=a.console,c={},h,l,p=9,q=[],r=25,m=["error","warn","info","debug","log"],v="assert clear count dir dirxml exception group groupCollapsed groupEnd profile profileEnd table time timeEnd trace".split(" "),
u;for(u=v.length;0<=(u-=1);)f(v[u]);for(u=m.length;0<=(u-=1);)b(u,m[u]);c.setLevel=function(a){p="number"===typeof a?a:9};c.setCallback=function(a,b,d){var c=q.length;h=a||null;l="boolean"===typeof b?b:!1;for(a=c-("number"===d?d:c);a<c;)e(q[a+=1])};return c}()})},"dojo/date/locale":function(){define("../_base/lang ../_base/array ../date ../cldr/supplemental ../i18n ../regexp ../string ../i18n!../cldr/nls/gregorian module".split(" "),function(g,e,f,b,a,d,c,h,l){function p(a,d,e,f){return f.replace(/([a-z])\1*/ig,
function(g){var h,l,k=g.charAt(0);g=g.length;var p=["abbr","wide","narrow"];switch(k){case "G":h=d[4>g?"eraAbbr":"eraNames"][0>a.getFullYear()?0:1];break;case "y":h=a.getFullYear();switch(g){case 1:break;case 2:if(!e.fullYear){h=String(h);h=h.substr(h.length-2);break}default:l=!0}break;case "Q":case "q":h=Math.ceil((a.getMonth()+1)/3);l=!0;break;case "M":case "L":h=a.getMonth();3>g?(h+=1,l=!0):(k=["months","L"==k?"standAlone":"format",p[g-3]].join("-"),h=d[k][h]);break;case "w":h=m._getWeekOfYear(a,
0);l=!0;break;case "d":h=a.getDate();l=!0;break;case "D":h=m._getDayOfYear(a);l=!0;break;case "e":case "c":if(h=a.getDay(),2>g){h=(h-b.getFirstDayOfWeek(e.locale)+8)%7;break}case "E":h=a.getDay();3>g?(h+=1,l=!0):(k=["days","c"==k?"standAlone":"format",p[g-3]].join("-"),h=d[k][h]);break;case "a":k=12>a.getHours()?"am":"pm";h=e[k]||d["dayPeriods-format-wide-"+k];break;case "h":case "H":case "K":case "k":l=a.getHours();switch(k){case "h":h=l%12||12;break;case "H":h=l;break;case "K":h=l%12;break;case "k":h=
l||24}l=!0;break;case "m":h=a.getMinutes();l=!0;break;case "s":h=a.getSeconds();l=!0;break;case "S":h=Math.round(a.getMilliseconds()*Math.pow(10,g-3));l=!0;break;case "v":case "z":if(h=m._getZone(a,!0,e))break;g=4;case "Z":k=m._getZone(a,!1,e);k=[0>=k?"+":"-",c.pad(Math.floor(Math.abs(k)/60),2),c.pad(Math.abs(k)%60,2)];4==g&&(k.splice(0,0,"GMT"),k.splice(3,0,":"));h=k.join("");break;default:throw Error("dojo.date.locale.format: invalid pattern char: "+f);}l&&(h=c.pad(h,g));return h})}function q(a,
b,d,c){var f=function(a){return a};b=b||f;d=d||f;c=c||f;var g=a.match(/(''|[^'])+/g),h="'"==a.charAt(0);e.forEach(g,function(a,c){a?(g[c]=(h?d:b)(a.replace(/''/g,"'")),h=!h):g[c]=""});return c(g.join(""))}function r(a,b,c,e){e=d.escapeString(e);c.strict||(e=e.replace(" a"," ?a"));return e.replace(/([a-z])\1*/ig,function(d){var e;e=d.charAt(0);var f=d.length,g="",h="";c.strict?(1<f&&(g="0{"+(f-1)+"}"),2<f&&(h="0{"+(f-2)+"}")):(g="0?",h="0{0,2}");switch(e){case "y":e="\\d{2,4}";break;case "M":case "L":e=
2<f?"\\S+?":"1[0-2]|"+g+"[1-9]";break;case "D":e="[12][0-9][0-9]|3[0-5][0-9]|36[0-6]|"+g+"[1-9][0-9]|"+h+"[1-9]";break;case "d":e="3[01]|[12]\\d|"+g+"[1-9]";break;case "w":e="[1-4][0-9]|5[0-3]|"+g+"[1-9]";break;case "E":case "e":case "c":e=".+?";break;case "h":e="1[0-2]|"+g+"[1-9]";break;case "k":e="1[01]|"+g+"\\d";break;case "H":e="1\\d|2[0-3]|"+g+"\\d";break;case "K":e="1\\d|2[0-4]|"+g+"[1-9]";break;case "m":case "s":e="[0-5]\\d";break;case "S":e="\\d{"+f+"}";break;case "a":f=c.am||b["dayPeriods-format-wide-am"];
g=c.pm||b["dayPeriods-format-wide-pm"];e=f+"|"+g;c.strict||(f!=f.toLowerCase()&&(e+="|"+f.toLowerCase()),g!=g.toLowerCase()&&(e+="|"+g.toLowerCase()),-1!=e.indexOf(".")&&(e+="|"+e.replace(/\./g,"")));e=e.replace(/\./g,"\\.");break;default:e=".*"}a&&a.push(d);return"("+e+")"}).replace(/[\xa0 ]/g,"[\\s\\xa0]")}var m={};g.setObject(l.id.replace(/\//g,"."),m);m._getZone=function(a,b,d){return b?f.getTimezoneName(a):a.getTimezoneOffset()};m.format=function(b,d){d=d||{};var c=a.normalizeLocale(d.locale),
e=d.formatLength||"short",c=m._getGregorianBundle(c),f=[],h=g.hitch(this,p,b,c,d);if("year"==d.selector)return q(c["dateFormatItem-yyyy"]||"yyyy",h);var l;"date"!=d.selector&&(l=d.timePattern||c["timeFormat-"+e])&&f.push(q(l,h));"time"!=d.selector&&(l=d.datePattern||c["dateFormat-"+e])&&f.push(q(l,h));return 1==f.length?f[0]:c["dateTimeFormat-"+e].replace(/\'/g,"").replace(/\{(\d+)\}/g,function(a,b){return f[b]})};m.regexp=function(a){return m._parseInfo(a).regexp};m._parseInfo=function(b){b=b||{};
var d=a.normalizeLocale(b.locale),d=m._getGregorianBundle(d),c=b.formatLength||"short",e=b.datePattern||d["dateFormat-"+c],f=b.timePattern||d["timeFormat-"+c],c="date"==b.selector?e:"time"==b.selector?f:d["dateTimeFormat-"+c].replace(/\{(\d+)\}/g,function(a,b){return[f,e][b]}),h=[];return{regexp:q(c,g.hitch(this,r,h,d,b)),tokens:h,bundle:d}};m.parse=function(a,b){var d=/[\u200E\u200F\u202A\u202E]/g,c=m._parseInfo(b),g=c.tokens,h=c.bundle,d=RegExp("^"+c.regexp.replace(d,"")+"$",c.strict?"":"i").exec(a&&
a.replace(d,""));if(!d)return null;var l=["abbr","wide","narrow"],k=[1970,0,1,0,0,0,0],p="",d=e.every(d,function(a,d){if(!d)return!0;var c=g[d-1],f=c.length,c=c.charAt(0);switch(c){case "y":if(2!=f&&b.strict)k[0]=a;else if(100>a)a=Number(a),c=""+(new Date).getFullYear(),f=100*c.substring(0,2),c=Math.min(Number(c.substring(2,4))+20,99),k[0]=a<c?f+a:f-100+a;else{if(b.strict)return!1;k[0]=a}break;case "M":case "L":if(2<f){if(f=h["months-"+("L"==c?"standAlone":"format")+"-"+l[f-3]].concat(),b.strict||
(a=a.replace(".","").toLowerCase(),f=e.map(f,function(a){return a.replace(".","").toLowerCase()})),a=e.indexOf(f,a),-1==a)return!1}else a--;k[1]=a;break;case "E":case "e":case "c":f=h["days-"+("c"==c?"standAlone":"format")+"-"+l[f-3]].concat();b.strict||(a=a.toLowerCase(),f=e.map(f,function(a){return a.toLowerCase()}));a=e.indexOf(f,a);if(-1==a)return!1;break;case "D":k[1]=0;case "d":k[2]=a;break;case "a":f=b.am||h["dayPeriods-format-wide-am"];c=b.pm||h["dayPeriods-format-wide-pm"];if(!b.strict){var n=
/\./g;a=a.replace(n,"").toLowerCase();f=f.replace(n,"").toLowerCase();c=c.replace(n,"").toLowerCase()}if(b.strict&&a!=f&&a!=c)return!1;p=a==c?"p":a==f?"a":"";break;case "K":24==a&&(a=0);case "h":case "H":case "k":if(23<a)return!1;k[3]=a;break;case "m":k[4]=a;break;case "s":k[5]=a;break;case "S":k[6]=a}return!0}),c=+k[3];"p"===p&&12>c?k[3]=c+12:"a"===p&&12==c&&(k[3]=0);c=new Date(k[0],k[1],k[2],k[3],k[4],k[5],k[6]);b.strict&&c.setFullYear(k[0]);var q=g.join(""),r=-1!=q.indexOf("d"),q=-1!=q.indexOf("M");
if(!d||q&&c.getMonth()>k[1]||r&&c.getDate()>k[2])return null;if(q&&c.getMonth()<k[1]||r&&c.getDate()<k[2])c=f.add(c,"hour",1);return c};var v=[],u={};m.addCustomFormats=function(a,b){v.push({pkg:a,name:b});u={}};m._getGregorianBundle=function(b){if(u[b])return u[b];var c={};e.forEach(v,function(d){d=a.getLocalization(d.pkg,d.name,b);c=g.mixin(c,d)},this);return u[b]=c};m.addCustomFormats(l.id.replace(/\/date\/locale$/,".cldr"),"gregorian");m.getNames=function(a,b,c,d){var e;d=m._getGregorianBundle(d);
a=[a,c,b];"standAlone"==c&&(c=a.join("-"),e=d[c],1==e[0]&&(e=void 0));a[1]="format";return(e||d[a.join("-")]).concat()};m.isWeekend=function(a,c){var d=b.getWeekend(c),e=(a||new Date).getDay();d.end<d.start&&(d.end+=7,e<d.start&&(e+=7));return e>=d.start&&e<=d.end};m._getDayOfYear=function(a){return f.difference(new Date(a.getFullYear(),0,1,a.getHours()),a)+1};m._getWeekOfYear=function(a,b){1==arguments.length&&(b=0);var c=(new Date(a.getFullYear(),0,1)).getDay(),d=Math.floor((m._getDayOfYear(a)+
(c-b+7)%7-1)/7);c==b&&d++;return d};return m})},"dojo/date":function(){define(["./has","./_base/lang"],function(g,e){var f={getDaysInMonth:function(b){var a=b.getMonth();return 1==a&&f.isLeapYear(b)?29:[31,28,31,30,31,30,31,31,30,31,30,31][a]},isLeapYear:function(b){b=b.getFullYear();return!(b%400)||!(b%4)&&!!(b%100)},getTimezoneName:function(b){var a=b.toString(),d="",c=a.indexOf("(");if(-1<c)d=a.substring(++c,a.indexOf(")"));else if(c=/([A-Z\/]+) \d{4}$/,a=a.match(c))d=a[1];else if(a=b.toLocaleString(),
c=/ ([A-Z\/]+)$/,a=a.match(c))d=a[1];return"AM"==d||"PM"==d?"":d},compare:function(b,a,d){b=new Date(+b);a=new Date(+(a||new Date));"date"==d?(b.setHours(0,0,0,0),a.setHours(0,0,0,0)):"time"==d&&(b.setFullYear(0,0,0),a.setFullYear(0,0,0));return b>a?1:b<a?-1:0},add:function(b,a,d){var c=new Date(+b),e=!1,f="Date";switch(a){case "day":break;case "weekday":var g;(a=d%5)?g=parseInt(d/5):(a=0<d?5:-5,g=0<d?(d-5)/5:(d+5)/5);var q=b.getDay(),r=0;6==q&&0<d?r=1:0==q&&0>d&&(r=-1);q+=a;if(0==q||6==q)r=0<d?2:
-2;d=7*g+a+r;break;case "year":f="FullYear";e=!0;break;case "week":d*=7;break;case "quarter":d*=3;case "month":e=!0;f="Month";break;default:f="UTC"+a.charAt(0).toUpperCase()+a.substring(1)+"s"}if(f)c["set"+f](c["get"+f]()+d);e&&c.getDate()<b.getDate()&&c.setDate(0);return c},difference:function(b,a,d){a=a||new Date;d=d||"day";var c=a.getFullYear()-b.getFullYear(),e=1;switch(d){case "quarter":b=b.getMonth();a=a.getMonth();b=Math.floor(b/3)+1;a=Math.floor(a/3)+1;e=a+4*c-b;break;case "weekday":c=Math.round(f.difference(b,
a,"day"));d=parseInt(f.difference(b,a,"week"));e=c%7;if(0==e)c=5*d;else{var g=0,p=b.getDay();a=a.getDay();d=parseInt(c/7);e=c%7;b=new Date(b);b.setDate(b.getDate()+7*d);b=b.getDay();if(0<c)switch(!0){case 6==p:g=-1;break;case 0==p:g=0;break;case 6==a:g=-1;break;case 0==a:g=-2;break;case 5<b+e:g=-2}else if(0>c)switch(!0){case 6==p:g=0;break;case 0==p:g=1;break;case 6==a:g=2;break;case 0==a:g=1;break;case 0>b+e:g=2}c=c+g-2*d}e=c;break;case "year":e=c;break;case "month":e=a.getMonth()-b.getMonth()+12*
c;break;case "week":e=parseInt(f.difference(b,a,"day")/7);break;case "day":e/=24;case "hour":e/=60;case "minute":e/=60;case "second":e/=1E3;case "millisecond":e*=a.getTime()-b.getTime()}return Math.round(e)}};e.mixin(e.getObject("dojo.date",!0),f);return f})},"dojo/cldr/supplemental":function(){define(["../_base/lang","../i18n"],function(g,e){var f={};g.setObject("dojo.cldr.supplemental",f);f.getFirstDayOfWeek=function(b){b={bd:5,mv:5,ae:6,af:6,bh:6,dj:6,dz:6,eg:6,iq:6,ir:6,jo:6,kw:6,ly:6,ma:6,om:6,
qa:6,sa:6,sd:6,sy:6,ye:6,ag:0,ar:0,as:0,au:0,br:0,bs:0,bt:0,bw:0,by:0,bz:0,ca:0,cn:0,co:0,dm:0,"do":0,et:0,gt:0,gu:0,hk:0,hn:0,id:0,ie:0,il:0,"in":0,jm:0,jp:0,ke:0,kh:0,kr:0,la:0,mh:0,mm:0,mo:0,mt:0,mx:0,mz:0,ni:0,np:0,nz:0,pa:0,pe:0,ph:0,pk:0,pr:0,py:0,sg:0,sv:0,th:0,tn:0,tt:0,tw:0,um:0,us:0,ve:0,vi:0,ws:0,za:0,zw:0}[f._region(b)];return void 0===b?1:b};f._region=function(b){b=e.normalizeLocale(b);b=b.split("-");var a=b[1];a?4==a.length&&(a=b[2]):a={aa:"et",ab:"ge",af:"za",ak:"gh",am:"et",ar:"eg",
as:"in",av:"ru",ay:"bo",az:"az",ba:"ru",be:"by",bg:"bg",bi:"vu",bm:"ml",bn:"bd",bo:"cn",br:"fr",bs:"ba",ca:"es",ce:"ru",ch:"gu",co:"fr",cr:"ca",cs:"cz",cv:"ru",cy:"gb",da:"dk",de:"de",dv:"mv",dz:"bt",ee:"gh",el:"gr",en:"us",es:"es",et:"ee",eu:"es",fa:"ir",ff:"sn",fi:"fi",fj:"fj",fo:"fo",fr:"fr",fy:"nl",ga:"ie",gd:"gb",gl:"es",gn:"py",gu:"in",gv:"gb",ha:"ng",he:"il",hi:"in",ho:"pg",hr:"hr",ht:"ht",hu:"hu",hy:"am",ia:"fr",id:"id",ig:"ng",ii:"cn",ik:"us","in":"id",is:"is",it:"it",iu:"ca",iw:"il",ja:"jp",
ji:"ua",jv:"id",jw:"id",ka:"ge",kg:"cd",ki:"ke",kj:"na",kk:"kz",kl:"gl",km:"kh",kn:"in",ko:"kr",ks:"in",ku:"tr",kv:"ru",kw:"gb",ky:"kg",la:"va",lb:"lu",lg:"ug",li:"nl",ln:"cd",lo:"la",lt:"lt",lu:"cd",lv:"lv",mg:"mg",mh:"mh",mi:"nz",mk:"mk",ml:"in",mn:"mn",mo:"ro",mr:"in",ms:"my",mt:"mt",my:"mm",na:"nr",nb:"no",nd:"zw",ne:"np",ng:"na",nl:"nl",nn:"no",no:"no",nr:"za",nv:"us",ny:"mw",oc:"fr",om:"et",or:"in",os:"ge",pa:"in",pl:"pl",ps:"af",pt:"br",qu:"pe",rm:"ch",rn:"bi",ro:"ro",ru:"ru",rw:"rw",sa:"in",
sd:"in",se:"no",sg:"cf",si:"lk",sk:"sk",sl:"si",sm:"ws",sn:"zw",so:"so",sq:"al",sr:"rs",ss:"za",st:"za",su:"id",sv:"se",sw:"tz",ta:"in",te:"in",tg:"tj",th:"th",ti:"et",tk:"tm",tl:"ph",tn:"za",to:"to",tr:"tr",ts:"za",tt:"ru",ty:"pf",ug:"cn",uk:"ua",ur:"pk",uz:"uz",ve:"za",vi:"vn",wa:"be",wo:"sn",xh:"za",yi:"il",yo:"ng",za:"cn",zh:"cn",zu:"za",ace:"id",ady:"ru",agq:"cm",alt:"ru",amo:"ng",asa:"tz",ast:"es",awa:"in",bal:"pk",ban:"id",bas:"cm",bax:"cm",bbc:"id",bem:"zm",bez:"tz",bfq:"in",bft:"pk",bfy:"in",
bhb:"in",bho:"in",bik:"ph",bin:"ng",bjj:"in",bku:"ph",bqv:"ci",bra:"in",brx:"in",bss:"cm",btv:"pk",bua:"ru",buc:"yt",bug:"id",bya:"id",byn:"er",cch:"ng",ccp:"in",ceb:"ph",cgg:"ug",chk:"fm",chm:"ru",chp:"ca",chr:"us",cja:"kh",cjm:"vn",ckb:"iq",crk:"ca",csb:"pl",dar:"ru",dav:"ke",den:"ca",dgr:"ca",dje:"ne",doi:"in",dsb:"de",dua:"cm",dyo:"sn",dyu:"bf",ebu:"ke",efi:"ng",ewo:"cm",fan:"gq",fil:"ph",fon:"bj",fur:"it",gaa:"gh",gag:"md",gbm:"in",gcr:"gf",gez:"et",gil:"ki",gon:"in",gor:"id",grt:"in",gsw:"ch",
guz:"ke",gwi:"ca",haw:"us",hil:"ph",hne:"in",hnn:"ph",hoc:"in",hoj:"in",ibb:"ng",ilo:"ph",inh:"ru",jgo:"cm",jmc:"tz",kaa:"uz",kab:"dz",kaj:"ng",kam:"ke",kbd:"ru",kcg:"ng",kde:"tz",kdt:"th",kea:"cv",ken:"cm",kfo:"ci",kfr:"in",kha:"in",khb:"cn",khq:"ml",kht:"in",kkj:"cm",kln:"ke",kmb:"ao",koi:"ru",kok:"in",kos:"fm",kpe:"lr",krc:"ru",kri:"sl",krl:"ru",kru:"in",ksb:"tz",ksf:"cm",ksh:"de",kum:"ru",lag:"tz",lah:"pk",lbe:"ru",lcp:"cn",lep:"in",lez:"ru",lif:"np",lis:"cn",lki:"ir",lmn:"in",lol:"cd",lua:"cd",
luo:"ke",luy:"ke",lwl:"th",mad:"id",mag:"in",mai:"in",mak:"id",man:"gn",mas:"ke",mdf:"ru",mdh:"ph",mdr:"id",men:"sl",mer:"ke",mfe:"mu",mgh:"mz",mgo:"cm",min:"id",mni:"in",mnk:"gm",mnw:"mm",mos:"bf",mua:"cm",mwr:"in",myv:"ru",nap:"it",naq:"na",nds:"de","new":"np",niu:"nu",nmg:"cm",nnh:"cm",nod:"th",nso:"za",nus:"sd",nym:"tz",nyn:"ug",pag:"ph",pam:"ph",pap:"bq",pau:"pw",pon:"fm",prd:"ir",raj:"in",rcf:"re",rej:"id",rjs:"np",rkt:"in",rof:"tz",rwk:"tz",saf:"gh",sah:"ru",saq:"ke",sas:"id",sat:"in",saz:"in",
sbp:"tz",scn:"it",sco:"gb",sdh:"ir",seh:"mz",ses:"ml",shi:"ma",shn:"mm",sid:"et",sma:"se",smj:"se",smn:"fi",sms:"fi",snk:"ml",srn:"sr",srr:"sn",ssy:"er",suk:"tz",sus:"gn",swb:"yt",swc:"cd",syl:"bd",syr:"sy",tbw:"ph",tcy:"in",tdd:"cn",tem:"sl",teo:"ug",tet:"tl",tig:"er",tiv:"ng",tkl:"tk",tmh:"ne",tpi:"pg",trv:"tw",tsg:"ph",tts:"th",tum:"mw",tvl:"tv",twq:"ne",tyv:"ru",tzm:"ma",udm:"ru",uli:"fm",umb:"ao",unr:"in",unx:"in",vai:"lr",vun:"tz",wae:"ch",wal:"et",war:"ph",xog:"ug",xsr:"np",yao:"mz",yap:"fm",
yav:"cm",zza:"tr"}[b[0]];return a};f.getWeekend=function(b){var a=f._region(b);b={"in":0,af:4,dz:4,ir:4,om:4,sa:4,ye:4,ae:5,bh:5,eg:5,il:5,iq:5,jo:5,kw:5,ly:5,ma:5,qa:5,sd:5,sy:5,tn:5}[a];a={af:5,dz:5,ir:5,om:5,sa:5,ye:5,ae:6,bh:5,eg:6,il:6,iq:6,jo:6,kw:6,ly:6,ma:6,qa:6,sd:6,sy:6,tn:6}[a];void 0===b&&(b=6);void 0===a&&(a=0);return{start:b,end:a}};return f})},"dojo/regexp":function(){define(["./_base/kernel","./_base/lang"],function(g,e){var f={};e.setObject("dojo.regexp",f);f.escapeString=function(b,
a){return b.replace(/([\.$?*|{}\(\)\[\]\\\/\+\-^])/g,function(b){return a&&-1!=a.indexOf(b)?b:"\\"+b})};f.buildGroupRE=function(b,a,d){if(!(b instanceof Array))return a(b);for(var c=[],e=0;e<b.length;e++)c.push(a(b[e]));return f.group(c.join("|"),d)};f.group=function(b,a){return"("+(a?"?:":"")+b+")"};return f})},"dojo/string":function(){define(["./_base/kernel","./_base/lang"],function(g,e){var f=/[&<>'"\/]/g,b={"\x26":"\x26amp;","\x3c":"\x26lt;","\x3e":"\x26gt;",'"':"\x26quot;","'":"\x26#x27;","/":"\x26#x2F;"},
a={};e.setObject("dojo.string",a);a.escape=function(a){return!a?"":a.replace(f,function(a){return b[a]})};a.rep=function(a,b){if(0>=b||!a)return"";for(var e=[];;){b&1&&e.push(a);if(!(b>>=1))break;a+=a}return e.join("")};a.pad=function(b,c,e,f){e||(e="0");b=String(b);c=a.rep(e,Math.ceil((c-b.length)/e.length));return f?b+c:c+b};a.substitute=function(a,b,f,l){l=l||g.global;f=f?e.hitch(l,f):function(a){return a};return a.replace(/\$\{([^\s\:\}]*)(?:\:([^\s\:\}]+))?\}/g,function(a,d,g){if(""==d)return"$";
a=e.getObject(d,!1,b);g&&(a=e.getObject(g,!1,l).call(l,a,d));return f(a,d).toString()})};a.trim=String.prototype.trim?e.trim:function(a){a=a.replace(/^\s+/,"");for(var b=a.length-1;0<=b;b--)if(/\S/.test(a.charAt(b))){a=a.substring(0,b+1);break}return a};return a})},"mw-browser-utils/DeprecatedBrowserCheck":function(){define(["dojo/_base/window","dojo/window"],function(g,e){var f={isBrowserValid:function(){var b=navigator.userAgent,a=b.match(/(msie|trident|edge(?=\/))\/?\s*(\d+)/i)||[];if(a[1]&&("MSIE"===
a[1]||"msie"===a[1]||/trident/i.test(a[1])))if(b=/\brv[ :]+(\d+)/g.exec(b)||[],12>parseInt(b[1]))return!1;return!0}};return{load:function(b,a,d){!f.isBrowserValid()&&b?g.global.location=b:d()}}})},"*now":function(g){g(['dojo/i18n!*preload*MOTW/nls/browsercheck*["en-us","ROOT"]'])}}});define("MOTW/browsercheck",[],1);